[package]
name = "porda-core"
version.workspace = true
edition.workspace = true

[dependencies]
porda-config = { workspace = true }
porda-vision = { workspace = true }
porda-capture = { workspace = true }
porda-inference = { workspace = true }
porda-overlay = { workspace = true }
porda-platform = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
